# Site settings
title: Desarrollador Android
email: androides@mindic.com
description: "Todo lo que necesitas saber para trabajar como desarrollador Android"
url: "http://androides.mindic.com"
twitter_username: mindicom


#mixpanel_dev_token: "18af4642364437ebc4a717819c6e0aec"
#mixpanel_prod_token: "d5e14496868d0a34f5d90b8701866cd0"

github_username:  jomargo

# Build settings
markdown: kramdown
permalink: pretty
baseurl: ""
include: ["_fonts", "_bg_videos"]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  sass_dir: _sass